site_name: My Docs
theme: 
  name: material
  palette:
    primary: purple 

plugins:
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: full
      post_url_format: "{date}/{slug}"
      post_url_max_categories: 2
      post_slugify_separator: "-"
      post_readtime: false
      draft: true

     